#
############################################
#Disabling this will disable this mods well being system
#-------------------------------------------
#Default: false
#-------------------------------------------
"Boolean: Enable Well Being" = false

