
#General settings
[general]
	#A list of buildings that are safe(r)
	excludedBuildings = []
	#List of mobs that can spawn in buildings together with their rarity
	mobs = [".5=minecraft:zombie"]
	#List of weapons that the mobs can have together with their rarity
	randomWeapons = [".5=null", ".2=minecraft:ender_pearl", ".2=minecraft:fishing_rod"]
	#List of helmets that the mobs can have together with their rarity
	randomHelmets = [".3=null"]
	#List of chestplates that the mobs can have together with their rarity
	randomChestplates = [".3=null" ]
	#List of leggings that the mobs can have together with their rarity
	randomLeggings = [".3=null" ]
	#List of boots that the mobs can have together with their rarity
	randomBoots = [".3=null" ]
	#List of effects that a mob can have. Note that multiple effects are possible
	randomEffects = [".5=minecraft:regeneration,1", ".1=minecraft:speed,1", ".1=minecraft:resistance,1"]
	#List of console commands to execute the first time a building is entered
	commandFirstTime = []
	#List of console commands to execute every time a building is entered
	commandEntered = []
	#List of console commands to execute when a building is cleared
	commandCleared = []
	#This message is given when the player tries to open a chest in a haunted building
	messageUnsafeBuilding = "The building isn't safe enough!"
	#This message is given when the player enters a haunted building for the first time
	messageBuildingHaunted = "You hear echo of the zombies..."
	#This message is given when the player clears a building
	messageBuildingCleared = "The building feels a lot safer now!"
	#This message is given when the player is halfway clearing a building
	messageBuildingHalfway = "About half way there! Keep going!"
	#The amount of ticks that the server waits before checking for new spawns
	#Range: 1 ~ 1000000
	serverTickTimeout = 60
	#The maximum amount of entities that can spawn near each other (of the same type)
	#Range: 1 ~ 200
	spawnMaxNearby = 12
	#The minimum distance between the player and newly spawned mobs
	#Range: 0.0 ~ 16.0
	minSpawnDistance = 2.0
	#The minimum health bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	minHealthBonus = 1.0
	#The maximum health bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	maxHealthBonus = 4.0
	#The minimum damage bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	minDamageBonus = 0.5
	#The maximum damage bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	maxDamageBonus = 1.0
	#The chance that a building is haunted
	#Range: 0.0 ~ 1.0
	hauntedChance = 0.75
	#The minimum amount of mobs that are spawned by a haunted building
	#Range: 1 ~ 10000
	minMobs = 10
	#The maximum amount of mobs that are spawned by a haunted building
	#Range: 1 ~ 10000
	maxMobs = 50
	#The chance that a building is haunted. This version is used in case the building is in a Lost City sphere
	#Range: 0.0 ~ 1.0
	sphereHauntedChance = 0.800000011920929
	#The minimum amount of mobs that are spawned by a haunted building. This version is used in case the building is in a Lost City sphere
	#Range: 1 ~ 10000
	sphereMinMobs = 10
	#The maximum amount of mobs that are spawned by a haunted building. This version is used in case the building is in a Lost City sphere
	#Range: 1 ~ 10000
	sphereMaxMobs = 50
	#If this is true then mobs will only spawn if the light level is low enough. Otherwise they spawn regardless of light level
	checkValidSpawn = false
	#If this is true then the player will be notified when a building is cleared
	announceCleared = true
	#If this is true then the player will be notified when he or she enters a haunted building
	announceEnter = true
	#If this is true then the player will get a message when he/she tries to open a locked chest
	announceChestLocked = true
	#If this is true then all chests will be locked until the building is cleared
	lockChestsUntilCleared = false
	#This option is only useful when 'lockChestsUntilCleared'. If true only vanilla chests will be locked. Otherwise all tile entities are locked
	lockOnlyChests = false

