
[options]
	#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
	preventdeath = true
	#Message that displays when Teleport is blocked
	blockedmessage = "%dim% doesn't exist."
	#Title for the Advancements
	craftedmessage = "%dim% Unlocked!"
	#Description for the Advancements
	description = "%dim% doesn't exist."
	#Comma seperated list of items that when crafted unlock the corresponding dimension
	craftitems = "minecraft:ender_eye,minecraft:ender_eye"
	#Comma seperated list of Dimension Resource Names
	dimresname = "minecraft:the_nether,minecraft:the_end"
	#Comma seperated list of Dimension Display Names
	dimnames = "Nether,End"

